services:
  mongo:
    image: mongo:8
    container_name: unibolsas-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: unibolsas

volumes:
  mongo_data:
